# Name of workflow to be displyed on Github Console
name: Build and Test Go Application

# Triggers the workflow on separate events 
on:
        push:
                branches:
                        -  '**'
        pull_request:
                branches:
                        - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# "build" workflow
        build:

                name: Build and Test Go Application
                #The type of runner on which job will run
                runs-on: ubuntu-latest

                steps: 
                        - name: Setup Go 1.16
                          uses: actions/setup-go@v2
                          with:
                                go-version: '1.16.3'

                        - name: Checkout Source Code
                          uses: actions/checkout@v2

                        - name: Build 
                          env: 
                                GOPROXY: "https://proxy.golang.org"
                          run: go build .

                        - name: Test Cases
                          run: go test -v .

                        - name: Check go vet 
                          run: go vet .

                        - name: Check Formatting using go fmt
                          run: |
                                gofmt -s -l .
                        
                                if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

                        - name: Run go lint 
                          run: |
                                curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
                                golangci-lint run
        notify:

                name: Notify on Slack

                runs-on: ubuntu-latest
                # Only run this workflow when "build" workflow succeeds
                needs: [build]

                # Only run this workflow if it is main branch on pull_request event
                if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'pull_request' }}

                steps: 
                        - uses: 8398a7/action-slack@v3
                          with:
                          status: ${{ job.status }}
                          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
                          env:
                                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
                          if: success() # Pick up events even if the job fails or is canceled.