name: slack-thread
'on':
  - push
  - issues
jobs:
  slack-thread:
    runs-on: ubuntu-20.04
    name: 'Sends a message to Slack when a push, a pull request or an issue is made'
    steps:
      - name: Send Slack Message
        uses: archive/github-actions-slack@master
        id: send-message
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: '${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}'
          slack-channel: C03UKUE4TD2
          slack-blocks: |-
            [
              {
                "block_id": "text1",
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Configuring branch: *main🚨*"
                }
              },
              {
                "type": "divider"
              },
              {
                "block_id": "text2",
                "type": "context",
                "elements": [
                  {
                    "type": "image",
                    "image_url": "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/1200px-Flag_of_Sweden.svg.png",
                    "alt_text": "images"
                  },
                  {
                    "type": "plain_text",
                    "text": "A push, a pull request or an issue is made "
                  }
                ]
              },
              {
                "type": "divider"
              }
            ]
      - name: Send "Slack Message" Result
        run: 'echo "Data - ${{ steps.send-message.outputs.slack-result }}"'
      - name: Some step in between
        run: echo "..."
      - name: Send Thread Message
        uses: archive/github-actions-slack@master
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: '${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}'
          slack-channel: >-
            ${{
            fromJson(steps.send-message.outputs.slack-result).response.channel
            }}
          # slack-text: "Issues\U0001F6B8 are available ![here](https://github.com/ShivamTyagi12345/Kritagya-Repository-Monitor-slackbot/issues) and new commits \U0001F6B8 can be seen at https://github.com/ShivamTyagi12345/Kritagya-Repository-Monitor-slackbot/actions"
          slack-blocks: |-
            [
              {
                "block_id": "text1",
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Check ![*Open or closed 🚨*](https://github.com/ShivamTyagi12345/Kritagya-Repository-Monitor-slackbot/issues)"
                }
              },
              {
                "type": "divider"
              },
              {
                "block_id": "text2",
                "type": "context",
                "elements": [
                  {
                    "type": "image",
                    "image_url": "https://unsplash.com/photos/V5vqWC9gyEU",
                    "alt_text": "images"
                  },
                  {
                    "type": "plain_text",
                    "text": "In case new issues arent raised, the notification is for New commits on branch **main**"
                  }
                ]
              },
              {
                "type": "divider"
              },
              {
                "block_id": "text3",
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Check ![*New commits🚨*](https://github.com/ShivamTyagi12345/Kritagya-Repository-Monitor-slackbot/actions)"
                }
              },
            ]
          slack-optional-thread_ts: >-
            ${{
            fromJson(steps.send-message.outputs.slack-result).response.message.ts
            }}
      - name: Send "Send Thread Message" Result
        run: 'echo "Data - ${{ steps.send-message.outputs.slack-result }}"'
